CREATE TABLE "clients" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar(250) UNIQUE NOT NULL,
  "phone" varchar(25) UNIQUE NOT NULL,
  "name" varchar(25) NOT NULL,
  "inn" varchar(12) UNIQUE NOT NULL,
  "status" varchar(20) DEFAULT 'ACTIVE',
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "client_blocks" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "client_id" integer NOT NULL,
  "block_type" varchar(32) NOT NULL,
  "reason" text NOT NULL,
  "blocked_by" varchar(128) NOT NULL,
  "created_at" datetime NOT NULL DEFAULT (now()),
  "expires_at" datetime,
  "unblocked_at" datetime
);

ALTER TABLE "client_blocks" ADD FOREIGN KEY ("client_id") REFERENCES "clients" ("id");
